### ISSUE TITLE
[BUG] Investigate error when publishing certain Contributions

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/rokwire-building-blocks-api#949]
**Describe the bug**
Some Contributions created using Postman are not getting published. E.g., https://api-dev.rokwire.illinois.edu/catalog/contributions/628d35a1cd1727000a1659e1 

**To Reproduce**
1. Create a Contribution using Postman
2. Review and publish the contribution from Catalog
3. See HTTP 400 error in Catalog.

**Expected behavior**
We should be able to publish Contributions created using Postman as well.

**Screenshots**

**Additional context**

**Comment by minump** [comment]
This issue is present in the develop branch and can be replicated in local as well.
The issue arises when posting a talent with null fields. When a talent is POSTed  with only the required fields, the rest of the fields are saved with value null. However, those fields are not nullable as per yaml file. So when a PUT is performed (which is done when the status is changed from Submitted to Published), the field does not match the yaml requirements (nullable vs string fields) and hence throws a 400 error.
